tables = {"dwc_oth_v_re_v_impuesto_sap": "select pct_impuesto, ind_tipo_imp, "
                                         "        cod_impuesto, cod_esquema, "
                                         "        cod_clasif, cod_emp_atlas"
                                         "        from hbgdwc.dwc_oth_v_re_v_impuesto_sap A",
          "booking": "select * "
                     "   from hbgdwc.svd_interface_booking_v6"
                     "  where creation_date = TO_DATE('{}', 'YYYY-MM-DD')",

          "dwc_bok_t_canco_hotel": "select seq_rec, seq_reserva, ind_tipo_regimen_fac, imp_margen_canal, "
                                   "        imp_margen_canco, imp_venta, ind_tipo_imp_vta_fac, cod_impuesto_vta_fac, "
                                   "        cod_clasif_vta_fac, cod_esquema_vta_fac, cod_empresa_vta_fac,"
                                   "        ind_tipo_regimen_con, imp_coste "
                                   "   from hbgdwc.dwc_bok_t_canco_hotel, hbgdwc.svd_interface_booking_v6 B"
                                   "  where creation_date = TO_DATE('{}', 'YYYY-MM-DD')"
                                   "    AND operative_incoming = seq_rec"
                                   "    AND booking_id = seq_reserva",

          "dwc_bok_t_canco_hotel_circuit": "select seq_rec, seq_reserva, ind_tipo_regimen_fac, imp_margen_canal, "
                                           "        imp_margen_canco, imp_venta, ind_tipo_imp_vta_fac, "
                                           "        cod_impuesto_vta_fac, cod_clasif_vta_fac, cod_esquema_vta_fac, "
                                           "        cod_empresa_vta_fac, ind_tipo_regimen_con, imp_coste"
                                           "   from hbgdwc.dwc_bok_t_canco_hotel_circuit, "
                                           "        hbgdwc.svd_interface_booking_v6 B"
                                           "  where creation_date = TO_DATE('{}', 'YYYY-MM-DD')"
                                           "    AND operative_incoming = seq_rec"
                                           "    AND booking_id = seq_reserva",

          "dwc_bok_t_canco_other": "select seq_rec, seq_reserva, ind_tipo_regimen_fac, imp_margen_canal, "
                                   "        imp_margen_canco, imp_venta, ind_tipo_imp_vta_fac, cod_impuesto_vta_fac, "
                                   "        cod_clasif_vta_fac, cod_esquema_vta_fac, cod_empresa_vta_fac,"
                                   "        ind_tipo_regimen_con, imp_coste"
                                   "   from hbgdwc.dwc_bok_t_canco_other, hbgdwc.svd_interface_booking_v6 B"
                                   "  where creation_date = TO_DATE('{}', 'YYYY-MM-DD')"
                                   "    AND operative_incoming = seq_rec"
                                   "    AND booking_id = seq_reserva",

          "dwc_bok_t_canco_transfer": "select seq_rec, seq_reserva, ind_tipo_regimen_fac, imp_margen_canal, "
                                      "        imp_margen_canco, imp_venta, ind_tipo_imp_vta_fac,  "
                                      "        cod_impuesto_vta_fac, cod_clasif_vta_fac, cod_esquema_vta_fac, "
                                      "        ind_tipo_regimen_con, imp_coste, "
                                      "        cod_empresa_vta_fac "
                                      "   from hbgdwc.dwc_bok_t_canco_transfer, "
                                      "        hbgdwc.svd_interface_booking_v6 B"
                                      "  where creation_date = TO_DATE('{}', 'YYYY-MM-DD')"
                                      "    AND operative_incoming = seq_rec"
                                      "    AND booking_id = seq_reserva",

          "dwc_bok_t_canco_endowments": "select seq_rec, seq_reserva, ind_tipo_regimen_fac, imp_margen_canal, "
                                        "        imp_margen_canco, imp_venta, ind_tipo_imp_vta_fac, "
                                        "        cod_impuesto_vta_fac, cod_clasif_vta_fac, cod_esquema_vta_fac, "
                                        "        cod_empresa_vta_fac, ind_tipo_regimen_con, imp_coste"
                                        "   from hbgdwc.dwc_bok_t_canco_endowments, hbgdwc.svd_interface_booking_v6 B"
                                        "  where creation_date = TO_DATE('{}', 'YYYY-MM-DD')"
                                        "    AND operative_incoming = seq_rec"
                                        "    AND booking_id = seq_reserva",

          "dwc_bok_t_canco_extra": "select seq_rec, seq_reserva, ord_extra, ind_tipo_regimen_fac, imp_margen_canal, "
                                   "        imp_margen_canco, imp_venta, ind_tipo_imp_vta_fac, cod_impuesto_vta_fac, "
                                   "        cod_clasif_vta_fac, cod_esquema_vta_fac, cod_empresa_vta_fac,"
                                   "        ind_tipo_regimen_con, imp_coste"
                                   "   from hbgdwc.dwc_bok_t_canco_extra, hbgdwc.svd_interface_booking_v6 B"
                                   "  where creation_date = TO_DATE('{}', 'YYYY-MM-DD')"
                                   "    AND operative_incoming = seq_rec"
                                   "    AND booking_id = seq_reserva",

          "dwc_bok_t_extra": "select grec_seq_rec, rres_seq_reserva, ord_extra, num_bono, cod_interface "
                             "   from hbgdwc.dwc_bok_t_extra, hbgdwc.svd_interface_booking_v6 B"
                             "  where creation_date = TO_DATE('{}', 'YYYY-MM-DD')"
                             "    AND operative_incoming = grec_seq_rec"
                             "    AND booking_id = rres_seq_reserva",

          "dwc_cli_dir_t_cd_discount_bond": "select num_bono, cod_interface, cod_campana "
                                            "   from hbgdwc.dwc_cli_dir_t_cd_discount_bond",
          "dwc_cli_dir_t_cd_campaign": "select cod_campana, cod_interface, ind_rentabilidad "
                                       "   from hbgdwc.dwc_cli_dir_t_cd_campaign",

          "dwc_bok_t_cost": "select sdiv_cod_divisa, fec_desde, fec_hasta, nro_unidades, nro_pax, ind_tipo_unid, "
                            "        ind_p_s, imp_unitario, grec_seq_rec, rres_seq_reserva, ind_tipo_registro, "
                            "        ind_facturable, ind_contra_apunte, rvp_ind_tipo_imp, rvp_cod_impuesto, "
                            "        rvp_cod_esquema, rvp_cod_clasif, rvp_cod_empresa, rext_ord_extra "
                            "   from hbgdwc.dwc_bok_t_cost",

          "sales_aux": "select seq_rec, seq_reserva, "
                       "       SUM ("
                       "             NVL ("
                       "                DECODE ("
                       "                   ind_tipo_regimen_fac,"
                       "                   'E', imp_margen_canal"
                       "                        * (1"
                       "                           - (1 / (1 + (vta.pct_impuesto / 100)))),"
                       "                   imp_venta"
                       "                   * (1 - (1 / (1 + (vta.pct_impuesto / 100))))"
                       "                   - (imp_venta - imp_margen_canal)"
                       "                     * (1 - (1 / (1 + (cpa.pct_impuesto / 100))))),"
                       "                0)) impuesto_canal "
                       "    from {}, "
                       "         aux r, "
                       "         impuesto_sap vta, "
                       "         impuesto_sap cpa"
                       "   where seq_rec = r.operative_incoming"
                       "     and seq_reserva = r.booking_id"
                       "     and ind_tipo_imp_vta_fac = vta.ind_tipo_imp"
                       "     and cod_impuesto_vta_fac = vta.cod_impuesto"
                       "     AND cod_clasif_vta_fac = vta.cod_clasif"
                       "     AND cod_esquema_vta_fac = vta.cod_esquema"
                       "     AND cod_empresa_vta_fac = vta.cod_emp_atlas"
                       "     AND ind_tipo_imp_vta_fac = cpa.ind_tipo_imp"
                       "     AND cod_impuesto_vta_fac = cpa.cod_impuesto"
                       "     AND cod_clasif_vta_fac = cpa.cod_clasif"
                       "     AND cod_esquema_vta_fac = cpa.cod_esquema"
                       "     AND cod_empresa_vta_fac = cpa.cod_emp_atlas"
                       "   GROUP BY seq_rec, seq_reserva",
          "sales_aux_extra": "select seq_rec, seq_reserva, "
                             "       SUM ("
                             "             NVL ("
                             "                DECODE ("
                             "                   ind_tipo_regimen_fac,"
                             "                   'E', imp_margen_canal"
                             "                        * (1"
                             "                           - (1 / (1 + (vta.pct_impuesto / 100)))),"
                             "                   imp_venta"
                             "                   * (1 - (1 / (1 + (vta.pct_impuesto / 100))))"
                             "                   - (imp_venta - imp_margen_canal)"
                             "                     * (1 - (1 / (1 + (cpa.pct_impuesto / 100))))),"
                             "                0)) impuesto_canal "
                             "    from {} e,"
                             "         aux r, "
                             "         impuesto_sap vta, "
                             "         impuesto_sap cpa"
                             "   where seq_rec = r.operative_incoming"
                             "     and seq_reserva = r.booking_id"
                             "     and ind_tipo_imp_vta_fac = vta.ind_tipo_imp"
                             "     and cod_impuesto_vta_fac = vta.cod_impuesto"
                             "     AND cod_clasif_vta_fac = vta.cod_clasif"
                             "     AND cod_esquema_vta_fac = vta.cod_esquema"
                             "     AND cod_empresa_vta_fac = vta.cod_emp_atlas"
                             "     AND ind_tipo_imp_vta_fac = cpa.ind_tipo_imp"
                             "     AND cod_impuesto_vta_fac = cpa.cod_impuesto"
                             "     AND cod_clasif_vta_fac = cpa.cod_clasif"
                             "     AND cod_esquema_vta_fac = cpa.cod_esquema"
                             "     AND cod_empresa_vta_fac = cpa.cod_emp_atlas"
                             "     AND not exists  (SELECT * "
                             "                        FROM bok_extra EXT,"
                             "                             discount_bond BON,"
                             "                             campaign CAM"
                             "                       WHERE e.seq_rec = EXT.grec_seq_rec"
                             "                         AND e.seq_reserva = EXT.rres_seq_reserva "
                             "                         AND e.ord_extra = EXT.ord_extra"
                             "                         AND EXT.num_bono = BON.num_bono"
                             "                         AND EXT.cod_interface = BON.cod_interface"
                             "                         AND BON.cod_campana = CAM.cod_campana"
                             "                         AND BON.cod_interface = CAM.cod_interface"
                             "                         AND CAM.ind_rentabilidad = 'N')"
                             "    GROUP BY seq_rec, seq_reserva",
          "cost_transfer_pricing_aux": "select seq_rec, seq_reserva, "
                                       "       SUM ("
                                       "             NVL ("
                                       "                DECODE ("
                                       "                   ind_tipo_regimen_con,"
                                       "                   'E', imp_margen_canco"
                                       "                        * (1"
                                       "                           - (1 / (1 + (vta.pct_impuesto / 100)))),"
                                       "                   (imp_coste + imp_margen_canco)"
                                       "                   * (1 - (1 / (1 + (vta.pct_impuesto / 100))))"
                                       "                   - (imp_coste)"
                                       "                     * (1 - (1 / (1 + (cpa.pct_impuesto / 100))))),"
                                       "                0)) impuesto_canco "
                                       "    from {} e,"
                                       "         aux r, "
                                       "         impuesto_sap vta, "
                                       "         impuesto_sap cpa"
                                       "   where seq_rec = r.operative_incoming"
                                       "     and seq_reserva = r.booking_id"
                                       "     and ind_tipo_imp_vta_fac = vta.ind_tipo_imp"
                                       "     and cod_impuesto_vta_fac = vta.cod_impuesto"
                                       "     AND cod_clasif_vta_fac = vta.cod_clasif"
                                       "     AND cod_esquema_vta_fac = vta.cod_esquema"
                                       "     AND cod_empresa_vta_fac = vta.cod_emp_atlas"
                                       "     AND ind_tipo_imp_vta_fac = cpa.ind_tipo_imp"
                                       "     AND cod_impuesto_vta_fac = cpa.cod_impuesto"
                                       "     AND cod_clasif_vta_fac = cpa.cod_clasif"
                                       "     AND cod_esquema_vta_fac = cpa.cod_esquema"
                                       "     AND cod_empresa_vta_fac = cpa.cod_emp_atlas"
                                       "   GROUP BY seq_rec, seq_reserva",
          "cost_transfer_pricing_aux_extra": "select seq_rec, seq_reserva, "
                                             "       SUM ("
                                             "             NVL ("
                                             "                DECODE ("
                                             "                   ind_tipo_regimen_con,"
                                             "                   'E', imp_margen_canco"
                                             "                        * (1"
                                             "                           - (1 / (1 + (vta.pct_impuesto / 100)))),"
                                             "                   (imp_coste + imp_margen_canco)"
                                             "                   * (1 - (1 / (1 + (vta.pct_impuesto / 100))))"
                                             "                   - (imp_coste)"
                                             "                     * (1 - (1 / (1 + (cpa.pct_impuesto / 100))))),"
                                             "                0)) impuesto_canco "
                                             "    from {} e,"
                                             "         aux r, "
                                             "         impuesto_sap vta, "
                                             "         impuesto_sap cpa"
                                             "   where seq_rec = r.operative_incoming"
                                             "     and seq_reserva = r.booking_id"
                                             "     and ind_tipo_imp_vta_fac = vta.ind_tipo_imp"
                                             "     and cod_impuesto_vta_fac = vta.cod_impuesto"
                                             "     AND cod_clasif_vta_fac = vta.cod_clasif"
                                             "     AND cod_esquema_vta_fac = vta.cod_esquema"
                                             "     AND cod_empresa_vta_fac = vta.cod_emp_atlas"
                                             "     AND ind_tipo_imp_vta_fac = cpa.ind_tipo_imp"
                                             "     AND cod_impuesto_vta_fac = cpa.cod_impuesto"
                                             "     AND cod_clasif_vta_fac = cpa.cod_clasif"
                                             "     AND cod_esquema_vta_fac = cpa.cod_esquema"
                                             "     AND cod_empresa_vta_fac = cpa.cod_emp_atlas"
                                             "     AND not exists  (SELECT * "
                                             "                        FROM bok_extra EXT,"
                                             "                             discount_bond BON,"
                                             "                             campaign CAM"
                                             "                       WHERE e.seq_rec = EXT.grec_seq_rec"
                                             "                         AND e.seq_reserva = EXT.rres_seq_reserva "
                                             "                         AND e.ord_extra = EXT.ord_extra"
                                             "                         AND EXT.num_bono = BON.num_bono"
                                             "                         AND EXT.cod_interface = BON.cod_interface"
                                             "                         AND BON.cod_campana = CAM.cod_campana"
                                             "                         AND BON.cod_interface = CAM.cod_interface"
                                             "                         AND CAM.ind_rentabilidad = 'N')"
                                             "    GROUP BY seq_rec, seq_reserva",

          "add_canco": "SELECT operative_incoming, booking_id, cst.sdiv_cod_divisa, r.booking_currency,"
                       "       r.creation_date, cst.fec_desde, cst.fec_hasta, cst.nro_unidades,"
                       "       cst.nro_pax, cst.ind_tipo_unid, cst.ind_p_s, cst.imp_unitario"
                       "                 FROM cost cst, aux r"
                       "                WHERE     cst.grec_seq_rec = r.operative_incoming"
                       "                      AND cst.rres_seq_reserva = r.booking_id"
                       "                      AND cst.ind_tipo_registro = 'DR'"
                       "                      AND cst.ind_facturable = 'S'"
                       "                      AND NOT EXISTS"
                       "                                 (SELECT 1"
                       "                                    FROM bok_extra EXT,"
                       "                                         discount_bond BON,"
                       "                                         campaign CAM"
                       "                                   WHERE CST.grec_seq_rec = EXT.grec_seq_rec"
                       "                                         AND CST.rres_seq_reserva = EXT.rres_seq_reserva"
                       "                                         AND CST.rext_ord_extra = EXT.ord_extra"
                       "                                         AND EXT.num_bono = BON.num_bono"
                       "                                         AND EXT.cod_interface = BON.cod_interface"
                       "                                         AND BON.cod_campana = CAM.cod_campana"
                       "                                         AND BON.cod_interface = CAM.cod_interface"
                       "                                         AND CAM.ind_rentabilidad = 'N')",

          "cost_transfer_pricing": "select F.operative_incoming, F.booking_id, "
                                   "       F.booking_currency, "
                                   "       SUM(NVL(impuesto_canco,0) + NVL(cost_field,0)) tax_cost_transfer_pricing "
                                   " FROM aux F LEFT JOIN canco C "
                                   "   ON F.operative_incoming = C.seq_rec"
                                   "  AND F.booking_id = C.seq_reserva"
                                   "  LEFT JOIN add_canco A "
                                   "   ON F.operative_incoming = A.operative_incoming"
                                   "  AND F.booking_id = A.booking_id"
                                   " GROUP BY F.operative_incoming, F.booking_id, F.booking_currency",

          "transfer_pricing_aux": "select seq_rec, seq_reserva, "
                                  "             NVL ("
                                  "                DECODE ("
                                  "                   ind_tipo_regimen_fac,"
                                  "                   'E', imp_margen_canal"
                                  "                        * (1"
                                  "                           - (1 / (1 + (vta.pct_impuesto / 100)))),"
                                  "                   imp_venta"
                                  "                   * (1 - (1 / (1 + (vta.pct_impuesto / 100))))"
                                  "                   - (imp_venta - imp_margen_canal)"
                                  "                     * (1 - (1 / (1 + (cpa.pct_impuesto / 100))))),"
                                  "                0) + "
                                  "                     DECODE ("
                                  "                        ind_tipo_regimen_con,"
                                  "                        'E', imp_margen_canco"
                                  "                             * (1"
                                  "                                - (1"
                                  "                                   / (1"
                                  "                                      + (vta.pct_impuesto"
                                  "                                         / 100)))),"
                                  "                        (imp_coste + imp_margen_canco)"
                                  "                        * (1"
                                  "                           - (1"
                                  "                              / (1"
                                  "                                 + (vta.pct_impuesto / 100))))"
                                  "                        - (imp_coste)"
                                  "                          * (1"
                                  "                             - (1"
                                  "                                / (1"
                                  "                                   + (cpa.pct_impuesto / 100))))) impuesto_canco "
                                  "    from {}, "
                                  "         aux r, "
                                  "         impuesto_sap vta, "
                                  "         impuesto_sap cpa"
                                  "   where seq_rec = r.operative_incoming"
                                  "     and seq_reserva = r.booking_id"
                                  "     and ind_tipo_imp_vta_fac = vta.ind_tipo_imp"
                                  "     and ind_tipo_imp_vta_fac = vta.ind_tipo_imp"
                                  "     and cod_impuesto_vta_fac = vta.cod_impuesto"
                                  "     AND cod_clasif_vta_fac = vta.cod_clasif"
                                  "     AND cod_esquema_vta_fac = vta.cod_esquema"
                                  "     AND cod_empresa_vta_fac = vta.cod_emp_atlas"
                                  "     AND ind_tipo_imp_vta_fac = cpa.ind_tipo_imp"
                                  "     AND cod_impuesto_vta_fac = cpa.cod_impuesto"
                                  "     AND cod_clasif_vta_fac = cpa.cod_clasif"
                                  "     AND cod_esquema_vta_fac = cpa.cod_esquema"
                                  "     AND cod_empresa_vta_fac = cpa.cod_emp_atlas",
          "transfer_pricing_aux_extra": "select seq_rec, seq_reserva, "
                                        "       "
                                        "             NVL ("
                                        "                DECODE ("
                                        "                   ind_tipo_regimen_fac,"
                                        "                   'E', imp_margen_canal"
                                        "                        * (1"
                                        "                           - (1 / (1 + (vta.pct_impuesto / 100)))),"
                                        "                   imp_venta"
                                        "                   * (1 - (1 / (1 + (vta.pct_impuesto / 100))))"
                                        "                   - (imp_venta - imp_margen_canal)"
                                        "                     * (1 - (1 / (1 + (cpa.pct_impuesto / 100))))),"
                                        "                0) + "
                                        "                     DECODE ("
                                        "                        ind_tipo_regimen_con,"
                                        "                        'E', imp_margen_canco"
                                        "                             * (1"
                                        "                                - (1"
                                        "                                   / (1"
                                        "                                      + (vta.pct_impuesto"
                                        "                                         / 100)))),"
                                        "                        (imp_coste + imp_margen_canco)"
                                        "                        * (1"
                                        "                           - (1"
                                        "                              / (1"
                                        "                                 + (vta.pct_impuesto / 100))))"
                                        "                        - (imp_coste)"
                                        "                          * (1"
                                        "                             - (1"
                                        "                                / (1"
                                        "                                   + (cpa.pct_impuesto / 100))))) "
                                        "                         impuesto_canco"
                                        "    from {} e, "
                                        "         aux r, "
                                        "         impuesto_sap vta, "
                                        "         impuesto_sap cpa"
                                        "   where seq_rec = r.operative_incoming"
                                        "     and seq_reserva = r.booking_id"
                                        "     and ind_tipo_imp_vta_fac = vta.ind_tipo_imp"
                                        "     and cod_impuesto_vta_fac = vta.cod_impuesto"
                                        "     AND cod_clasif_vta_fac = vta.cod_clasif"
                                        "     AND cod_esquema_vta_fac = vta.cod_esquema"
                                        "     AND cod_empresa_vta_fac = vta.cod_emp_atlas"
                                        "     AND ind_tipo_imp_vta_fac = cpa.ind_tipo_imp"
                                        "     AND cod_impuesto_vta_fac = cpa.cod_impuesto"
                                        "     AND cod_clasif_vta_fac = cpa.cod_clasif"
                                        "     AND cod_esquema_vta_fac = cpa.cod_esquema"
                                        "     AND cod_empresa_vta_fac = cpa.cod_emp_atlas"
                                        "     AND not exists  (SELECT * "
                                        "                        FROM bok_extra EXT,"
                                        "                             discount_bond BON,"
                                        "                             campaign CAM"
                                        "                       WHERE e.seq_rec = EXT.grec_seq_rec"
                                        "                         AND e.seq_reserva = EXT.rres_seq_reserva "
                                        "                         AND e.ord_extra = EXT.ord_extra"
                                        "                         AND EXT.num_bono = BON.num_bono"
                                        "                         AND EXT.cod_interface = BON.cod_interface"
                                        "                         AND BON.cod_campana = CAM.cod_campana"
                                        "                         AND BON.cod_interface = CAM.cod_interface"
                                        "                         AND CAM.ind_rentabilidad = 'N')",
          "tax_transfer_pricing": "select F.operative_incoming, F.booking_id, "
                                  "       F.booking_currency, "
                                  "       SUM(NVL(impuesto_canco,0) + NVL(cost_field,0)) tax_transfer_pricing "
                                  " FROM aux F LEFT JOIN canco C "
                                  "   ON F.operative_incoming = C.seq_rec"
                                  "  AND F.booking_id = C.seq_reserva"
                                  "  LEFT JOIN add_canco A "
                                  "   ON F.operative_incoming = A.operative_incoming"
                                  "  AND F.booking_id = A.booking_id"
                                  " GROUP BY F.operative_incoming, F.booking_id, F.booking_currency",
          # query for functions.py
          "dwc_gen_t_general_currency": "SELECT decimales, cod_divisa "
                                        "   FROM hbgdwc.dwc_gen_t_general_currency",
          }
